### ISSUE TITLE
Re sell not active issue, but it’s active 

### ISSUE THREAD

**Issue by mjkdubai** [joshcarty/ra-resale#2]
Hi, I signed for the this event once it sold out. 
The re sell was open, but after couple weeks it wasn’t (it just doesn’t say that)
https://www.residentadvisor.net/events/1310501

I did reserve email today 5 am that tickets were available. But I was sleep of course. 
No I try to sign in again, it doesn’t allow me, and the issue is “re sell isn’t open” 
But I think it’s open. Cause 2 of my mates found tickets today. 
And I am sure of that, cause the members attending number went up. 
I’ve been checking the event page multiple times a day, so I event memorized the attending number lol 
Can we please solve this. I think it’s just a bug on RA website. Cause my mate says he can re sell his ticket from RA portal still. 

![ACE376BF-5270-4788-B218-1B7F124F0055](https://user-images.githubusercontent.com/55195489/65360531-53344500-dc11-11e9-87fc-12eb1a8623e8.png)
![610F87CB-C1FB-4A7D-AA71-02123B18E0C0](https://user-images.githubusercontent.com/55195489/65360534-53ccdb80-dc11-11e9-987f-576d63b48a4d.png)
![537B1151-0F0B-497D-9A8D-AC8EAFB059CC](https://user-images.githubusercontent.com/55195489/65360535-53ccdb80-dc11-11e9-8420-79a3f00e7105.jpeg)

**Comment by joshcarty** [comment]
Hey - that sucks you haven't been able to get a ticket.

You're right it looks like a bug in the RA website. Your event doesn't have the "Resale active" notice under the tickets like it does [here](https://www.residentadvisor.net/events/1297002).

It is possible that the promotor is uploading new tickets rather than them being resold. The fact your mate can resell through the portal does contradict this though. And the fact you were able to get that first alert.

I'm reluctant to disable the validation that checks if resale is active for events. However, I can reenable alerts for users that had already subscribed to this particular event. I hope that helps.

**Comment by mjkdubai** [comment]
I just got an email like 14 minutes ago, that ticket is available. I was literally in the fucking bathroom :) and the attending count went up by 1. So I think it’s an RA bug.
Cause I asked the promoter and they said they don’t have any tickets to put online anymore.

**Comment by mjkdubai** [comment]
Like can I just tweet you on twitter whenever I get an email and I need to be subscribed?
Cause what I did understand, every time an email is sent. I need subscribe again.

**Comment by joshcarty** [comment]
I've reenabled it a couple of times and emails are being sent but there don't appear to be tickets. I wonder if there is something else wrong here.

**Comment by mjkdubai** [comment]
I was wondering what’s happening like I got 3-4 emails. But I am sure there wasn’t tickets cause you the the number attending is stuck. 
I might just contact RA. Or just lose hope ahha
